### PR TITLE
add Get-CSNetSessionEnumPermission

### PR DESCRIPTION
**Pull request by vrdse**
This Pull Request adds a new audit functin called "Get-CSNetSessionEnumPermission". This is the "audit counterpart" of NetCease (NetSessionEnum Hardening), see also https://gallery.technet.microsoft.com/Net-Cease-Blocking-Net-1e8dcb5b.

### CODE REVIEW

**Comment by mattifestation** [comment]
My apologies for being a total slacker on this. Thanks a lot for the PR!!! I like how you modeled everything after the existing functions. The only thing I'd ask is that functions that return security descriptors do so in a consistent fashion. For the functions that support -IncludeACL, [you'll see](https://github.com/PowerShellMafia/CimSweep/blob/master/CimSweep/Core/CoreFunctions.ps1#L1301-L1326) that they all return objects that derive from the System.Security.AccessControl.ObjectSecurity class. Could you maybe rework this to support that object type? The reason I like that is because I'd like to be able to see distinguish allow from deny ACEs as well as to have the access rights properly parsed out. Thanks!

**Comment by mattifestation** [comment]
Looks great! Thanks for making the change!!!

**Comment by vrdse** [comment]
@mattifestation although I liked my output more, I totaly get your point of consistency. 😉 Glad this is now merged, thank you too!

**Comment by mattifestation** [comment]
Your output was definitely cleaner originally but this version will empower uses to make slightly more educated decisions about the security descriptor. And yes, I'm just OCD about consistency. ;)

Cheers,
Matt

**Pull request merged**
